// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEuiGhw5okacCaLiEXLRzKx4U1A9QnrBY',
    appId: '1:91224273083:web:9780dbccfd2854566bb99e',
    messagingSenderId: '91224273083',
    projectId: 'my-cool-project-db75d',
    authDomain: 'my-cool-project-db75d.firebaseapp.com',
    storageBucket: 'my-cool-project-db75d.firebasestorage.app',
    measurementId: 'G-042EVFPSX1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDvB6eXgYt_KzBG1q5_EsH-z4ZYCIFBAU',
    appId: '1:91224273083:android:26e9b1364fd3aea66bb99e',
    messagingSenderId: '91224273083',
    projectId: 'my-cool-project-db75d',
    storageBucket: 'my-cool-project-db75d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC94vp723SQKkEpMccC8P-eb8IIo49s8JM',
    appId: '1:91224273083:ios:5ece36d4368e5d1d6bb99e',
    messagingSenderId: '91224273083',
    projectId: 'my-cool-project-db75d',
    storageBucket: 'my-cool-project-db75d.firebasestorage.app',
    iosBundleId: 'com.example.agenticapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC94vp723SQKkEpMccC8P-eb8IIo49s8JM',
    appId: '1:91224273083:ios:5ece36d4368e5d1d6bb99e',
    messagingSenderId: '91224273083',
    projectId: 'my-cool-project-db75d',
    storageBucket: 'my-cool-project-db75d.firebasestorage.app',
    iosBundleId: 'com.example.agenticapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAEuiGhw5okacCaLiEXLRzKx4U1A9QnrBY',
    appId: '1:91224273083:web:363d124ebe317f516bb99e',
    messagingSenderId: '91224273083',
    projectId: 'my-cool-project-db75d',
    authDomain: 'my-cool-project-db75d.firebaseapp.com',
    storageBucket: 'my-cool-project-db75d.firebasestorage.app',
    measurementId: 'G-YHZYHW907Q',
  );

}